#!/bin/bash
TAG=$(git describe --tags --abbrev=0 2>/dev/null)
VERSION=${TAG#v}
if [ -n "$VERSION" ]; then
  node -e "
    const fs = require('fs');
    const pkg = require('./client/package.json');
    pkg.version = '$VERSION';
    fs.writeFileSync('./client/package.json', JSON.stringify(pkg, null, 2) + '\n');
  "
  git add client/package.json
fi
